# Generated by Django 5.1.7 on 2025-04-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0005_remove_valve_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='location_link',
        ),
    ]
