# Generated by Django 5.1.5 on 2025-04-22 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0006_remove_valve_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='current_condition',
            field=models.FloatField(help_text='Enter a number for current condition (e.g., 50.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='valve',
            name='full_open_condition',
            field=models.FloatField(help_text='Enter a number for full open condition (e.g., 100.0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
