# Generated by Django 5.1.5 on 2025-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0007_alter_valve_current_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='previous_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
