# Generated by Django 5.1.7 on 2025-04-25 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0008_alter_valve_previous_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='mid_point',
            field=models.FloatField(default=0.5, help_text='Mid-point of the curve (default 0.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='valve',
            name='steepness',
            field=models.FloatField(default=12.5, help_text='Steepness factor (default 12.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
