# Generated by Django 5.1.5 on 2025-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0009_valve_mid_point_valve_steepness'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
