# Generated by Django 5.1.5 on 2025-05-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0010_valve_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valve',
            old_name='image',
            new_name='area_image',
        ),
    ]
