# Generated by Django 5.1.7 on 2025-05-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('valves', '0011_rename_image_valve_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area'),
        ),
    ]
