# Generated by Django 5.1.7 on 2025-05-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('valves', '0013_remove_valve_area_valve_provide_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='provide_area',
        ),
        migrations.AddField(
            model_name='valve',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valves', to='area.area'),
        ),
    ]
