# Generated by Django 5.1.7 on 2025-05-19 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0014_remove_valve_provide_area_valve_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='mid_point',
            field=models.FloatField(blank=True, default=0.5, help_text='Mid-point of the curve (default 0.5).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='valve',
            name='steepness',
            field=models.FloatField(blank=True, default=12.5, help_text='Steepness factor (default 12.5).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
