# Generated by Django 5.1.5 on 2025-04-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectiontype', '0005_delete_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('file_number', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='connectiontype.connectiontype')),
                ('to_connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='connectiontype.connectiontype')),
            ],
        ),
    ]
