# Generated by Django 5.1.5 on 2025-04-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(editable=False, max_length=255, unique=True)),
                ('complaint_type', models.CharField(max_length=255)),
                ('ticket_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('return_for_review', 'Return for Review')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
        ),
    ]
