# Generated by Django 5.1.7 on 2025-04-25 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
