# Generated by Django 5.1.7 on 2025-05-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('complaints', '0004_alter_complaint_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
    ]
