# Generated by Django 5.1.5 on 2025-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontype', '0002_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('assistant_engineer', 'Assistant Engineer'), ('fo', 'FO'), ('site_inspector', 'Site Inspector'), ('completed', 'Completed')], default='assistant_engineer', max_length=20),
        ),
    ]
