# Generated by Django 5.1.5 on 2025-04-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontype', '0003_alter_connection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('file_number', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('assistant_engineer', 'Assistant Engineer'), ('fo', 'FO'), ('site_inspector', 'Site Inspector'), ('completed', 'Completed')], default='assistant_engineer', max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_connection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_conversions', to='connectiontype.connectiontype')),
                ('to_connection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_conversions', to='connectiontype.connectiontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
