# Generated by Django 5.1.5 on 2025-04-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontype', '0004_conversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversion',
        ),
    ]
