# Generated by Django 5.1.5 on 2025-04-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectiontype', '0005_delete_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='date',
        ),
    ]
